apiVersion: batch/v1
kind: Job
metadata:
  name: chs091-grasp-scoring # Replace with something like "${USER_NAME}-{EXP_NAME}"
  namespace: ucsd-haosulab
  labels:
    user: chs091  # Specify your name
spec:
  ttlSecondsAfterFinished: 86400  # Wait one day to delete completed jobs
  template:
    spec:
      containers:
      - name: gpu-container
        image: aufish1999/cuda:1.0  # docker image
        imagePullPolicy: Always
        command : ['sh', '-c', '/cephfs/chs091/setup_and_score.sh']
        resources:
          requests:
            cpu: "1"
            memory: "2Gi"
            nvidia.com/gpu: 1
          limits:
            cpu: "2"
            memory: "8Gi"
            nvidia.com/gpu: 1
        volumeMounts:
          - name: cephfs
            mountPath: /cephfs
          - name: dshm
            mountPath: /dev/shm
      volumes:
      - name: dshm  # shared memory
        emptyDir:
          medium: Memory
      - name: cephfs
        persistentVolumeClaim:
          claimName: haosulab-cephfs
      restartPolicy: Never
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nautilus.io/group
                operator: In
                values:
                - haosu
              - key: env
                operator: In
                values:
                - production
              - key: gpu-type
                operator: In
                values:
                - 1080Ti
                - 2080Ti
  backoffLimit: 2