apiVersion: v1
kind: Pod
metadata:
  name: chs091-connection  # Replace with something like "${USER_NAME}-{EXP_NAME}"
  namespace: ucsd-haosulab
  labels:
    user: chs091  # Specify your name
spec:
  containers:
  - name: gpu-container
    image: aufish1999/cuda:1.0
    imagePullPolicy: Always
    command : ['sh', '-c', 'sleep infinity']
    resources:
      requests:
        cpu: "1"
        memory: "8Gi"
        nvidia.com/gpu: 1
      limits:
        cpu: "2"
        memory: "8Gi"
        nvidia.com/gpu: 1
    volumeMounts:
    - name: cephfs
      mountPath: /cephfs
  volumes:
  - name: cephfs
    persistentVolumeClaim:
      claimName: haosulab-cephfs
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nautilus.io/group
            operator: In
            values:
            - haosu
          - key: env
            operator: In
            values:
            - production
          - key: gpu-type
            operator: In
            values:
            - 1080Ti
            - 2080Ti
  # nodeSelector: 
  #     kubernetes.io/hostname: "k8s-haosu-01.sdsc.optiputer.net"